### ISSUE TITLE
Permission to edit the wiki?

### ISSUE THREAD

**Issue by mc-oofert** [evilfactory/Barotrauma-lua-attempt#13]
i would like to add more documentation

**Comment by evilfactory** [comment]
Is there any way to allow anyone to request changes to the wiki in github? If not, is there an alternative wiki that supports this? gonna look up.

**Comment by mc-oofert** [comment]
"You can edit wikis directly on GitHub, or you can edit wiki files locally. By default, only people with write access to your repository can make changes to wikis, although you can allow everyone on GitHub to contribute to a wiki in a public repository. For more information, see "Changing access permissions for wikis".

https://docs.github.com/en/communities/documenting-your-project-with-wikis/changing-access-permissions-for-wikis

**Comment by evilfactory** [comment]
Disabled the option, should work now?

**Comment by mc-oofert** [comment]
should also consider making a discord server for this incase people want to ask questions or get help

**Comment by mc-oofert** [comment]
also wiki is now editable

**Comment by evilfactory** [comment]
we actually have a discord server, it's just not public anywhere because we mostly use it for hosting pings: https://discord.gg/f9zvNNuxu9
