### ISSUE TITLE
How to get the subs field reference of NetLobbyScreen?

### ISSUE THREAD

**Issue by zhu-rengong** [evilfactory/Barotrauma-lua-attempt#23]
There is a trick to force all players to update the lobby, looks like:  
```lua
    client.LastRecvLobbyUpdate = 0
    Networking.ClientWriteLobby(client)
    client.LastRecvLobbyUpdate = Game.NetLobbyScreen.LastUpdateID
```
the purpose is to add a new submarine in a multiplayer campaign, and it works.  
But I cannot remove the submarine from the listbox in the lobby.
Because a field named 'subs' from Barotrauma.NetLobbyScreen in WindowsServer is Private:
`private List<SubmarineInfo> subs;`
And no method can reference it.  
I don't know how to get it, Is there any way to solve it?

**Comment by evilfactory** [comment]
I can make the field public, to make it so you can do this:
```lua
local test = Game.NetLobbyScreen.subs
test[4] = nil
Game.NetLobbyScreen = test
```
not sure if it's the best way to do it

**Comment by evilfactory** [comment]
Found a way to make it accessible via Lua without making it public, this should work now

**Comment by zhu-rengong** [comment]
Cool! but for some reasons I can’t test it yet. Now I have an idea. What do you think of extracting the method of turning private members into public members? Because I think that directly modifying the member's access right in the source code may cause a certain degree of difficulty in later maintenance. If we can modify the access right through the lua script, then there is no need for you to modify the source code.

**Comment by evilfactory** [comment]
Sounds a good idea, i was thinking also of using [Harmony](https://github.com/pardeike/Harmony) for hooks, but adding this functionality would probably prevent any sandboxing? I guess it's possible to just sandbox it on the Lua side, or maybe not have any sandboxing at all.

I'm going to experiment with Harmony, to see if it would be feasible to shift most of the C# code to Lua.

**Comment by zhu-rengong** [comment]
Except this feature!

And problem has solved, works correctly.
