### ISSUE TITLE
After updating on the workshop, opening the server will crash

### ISSUE THREAD

**Issue by zhu-rengong** [evilfactory/Barotrauma-lua-attempt#28]
There are four servers on our side that cannot open the dedicatedserver.
![T@`C E~7Q%I{$GI ~OOH2 6](https://user-images.githubusercontent.com/73634685/142572471-83a87785-4976-40b2-88a5-2d7568c8c7c0.png)
The server process has closed unexpectedly. A crash report (servercrashreport.log) may have been generated in the game's root directory.

Servercrashreport.log is not generated

**Comment by evilfactory** [comment]
Can you manually execute the DedicatedServer.exe from the Mods/LuaForBarotrauma, to show the crash errors

**Comment by zhu-rengong** [comment]
fail to execute, instantly crash when open.

**Comment by evilfactory** [comment]
Open cmd in the directory and type in DedicatedServer, so it doesn't immediately close

**Comment by evilfactory** [comment]
I might have fixed the error, MonoMod.Common.dll was missing from the workshop version, but it somehow didn't error on my computer, so i'm not sure if this was the problem, please let me know.

**Comment by zhu-rengong** [comment]
```
PS D:\Program Files (x86)\Steam\steamapps\common\Barotrauma\Mods\LuaForBarotrauma> .\DedicatedServer.exe
Error:
  An assembly specified in the application dependencies manifest (DedicatedServer.deps.json) was not found:
    package: 'Mono.Cecil', version: '0.11.4'
    path: 'lib/netstandard2.0/Mono.Cecil.Mdb.dll'
```
Maybe it's because of this reason

**Comment by evilfactory** [comment]
Updated workshop version and added the missing dlls, let me know if the error still happens

**Comment by zhu-rengong** [comment]
working correctly.
