### ISSUE TITLE
Nullref exception in ClientWriteLobby

### ISSUE THREAD

**Issue by zhu-rengong** [evilfactory/Barotrauma-lua-attempt#43]
after joining a lua-server, if round has already started, the game can't normally load net lobby screen until round ended:
![8{ U 6SMOGTW6_RX)T_Q0MA](https://user-images.githubusercontent.com/73634685/155738279-5d9e68ef-6428-4e9e-9a65-77869176b242.jpg)

The server console will pop up constantly:
```
Failed to write a network message for the client "zhurengong"! {Object reference not set to an instance of an object.}
   at Barotrauma.Networking.GameServer.ClientWriteLobby(Client c) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Networking\GameServer.cs:line 1849
   at Barotrauma.Networking.GameServer.ClientWrite(Client c) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Networking\GameServer.cs:line 0
   at Barotrauma.Networking.GameServer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Networking\GameServer.cs:line 615
```

Joining other lua servers will meet the same problem.

**Comment by evilfactory** [comment]
maybe the server needs to have more than 0 players?

**Comment by zhu-rengong** [comment]
I don't know, but there are some servers that use LuaForBarotrauma, you can check:
1. Custom traitor missions(read description)
2. (PROJECT)Ketsal - RUS RP
3. Server (I don't know password)
4. 【BOS】蓝海之家 生化危机 潮汐崩腾

**Comment by evilfactory** [comment]
I joined a server called The Happy Traitor - Traitor Mod which uses LuaForBarotrauma, and i loaded fine into the lobby, without issues (round started)

**Comment by evilfactory** [comment]
i know the server `Custom traitor missions(read description)`, it doesn't use LuaForBarotrauma as far i know

**Comment by zhu-rengong** [comment]
Joining the [?]The Happy Traitor server does not have this problem, but joining the others does. you can try to join ```(PROJECT)Ketsal - RUS RP```

**Comment by evilfactory** [comment]
Joined the server and i can confirm that i had the problem, but i'm not sure if it was caused by LuaForBarotrauma, maybe there's a mod causing this?

**Comment by evilfactory** [comment]
> ```
> Failed to write a network message for the client "zhurengong"! {Object reference not set to an instance of an object.}
>    at Barotrauma.Networking.GameServer.ClientWriteLobby(Client c) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Networking\GameServer.cs:line 1849
>    at Barotrauma.Networking.GameServer.ClientWrite(Client c) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Networking\GameServer.cs:line 0
>    at Barotrauma.Networking.GameServer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Networking\GameServer.cs:line 615
> ```

you don't get this error you mentioned?

**Comment by zhu-rengong** [comment]
Just got this error, same as the released version.

**Comment by evilfactory** [comment]
![image](https://user-images.githubusercontent.com/36804725/155750664-f5258070-1da5-4a86-a0fd-64657b8d982d.png)
I think this try catch is preventing the debugger from handling the exception, can you try removing it and testing again? (don't forget to attach the visual studio debugger)

**Comment by zhu-rengong** [comment]
Uh, I don't know how to debug, my computer can't be exposed to the public network, and my server also doesn't have enough conditions to do these things.

**Comment by evilfactory** [comment]
someone reported in the barotrauma discord server the same error
![unknown](https://user-images.githubusercontent.com/36804725/155761077-814c6b45-2381-4fcc-96f4-8802cfb6c99d.png)
so this is definitely not caused by LuaForBarotrauma

**Comment by zhu-rengong** [comment]
It seems yes, since no one reported this obvious issue for a long time, so I thought it was not a vanilla issue before. Then I had to compile a temporary project myself. ![)M14SEALAJW$TP)X%O~E)~P](https://user-images.githubusercontent.com/73634685/155827966-c2bfa97e-0d25-4a41-95c7-4be63f9060cd.png)
