### ISSUE TITLE
Doors/Hatches lagging + lagging the circuits connected to them?

### ISSUE THREAD

**Issue by oiltanker** [evilfactory/Barotrauma-lua-attempt#45]
- [+] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Doors lagging when are connected to auto-close circuit + animation of closing/opening also is lagging.
Circuitry lag: the delay component is set to 2 seconds, have to wait +- 10 sec for it to close.

**Steps To Reproduce**
1. Open game.
2. Select a sub to test with.
3. Test it in sub editor, make sure doors work ok.
4. Exit sub editor.
5. Repeat steps 3-4, with the last time exiting in the main menu instead of editor.
6. Host server (in-game), start with bots (I started with 2 (3 with fill option)).
7. Maneuver sub, shoot guns, open/close doors etc. (should work fine at this moment).
8. End mission, disconnect, enter sub editor, test sub.
9. Doors should lag as described.

**Version**
Windows, latest default in steam, latest workshop mod version

**Additional information**
If bug not present I can demo in discord, just dm.

**Comment by evilfactory** [comment]
Fixed in https://github.com/evilfactory/Barotrauma-lua-attempt/commit/ffeef7a0d3b3d97698dbdc47ebd5536cec876b67 , mapEntityUpdateInterval and gapUpdateInterval aren't preserved between sessions anymore

**Comment by oiltanker** [comment]
hmm, I do not know, but it did really mess me up yesterday, everything which is slightly more smart than a default auto-close circuit + delay of 2 seconds has a consistent lag.

**Comment by oiltanker** [comment]
I would personally say yes. But it's your discretion.

**Comment by evilfactory** [comment]
A temporary workaround would be typing `cl_reloadlua` in your console, while in the sub editor
