### ISSUE TITLE
JsonTableConverter is good

### ISSUE THREAD

**Issue by zhu-rengong** [evilfactory/Barotrauma-lua-attempt#52]
lua itself doesn't recognize some unicode sequences like `\u6211\u6212\u6213\u1362\u1462\u1562` <=> `我戒戓።ᑢᕢ`, for example:
```
local result = string.gsub("我戒戓።ᑢᕢ", '[%z\1-\31\\"]', function (c)
    return "\\" .. string.format("u%04x", c:byte())
end)
print(result)

-- output:
-- \u003f\u003f\u003f
```
the output wasn't what we expected, so lua's pure json library (such as [json.lua by rxi](https://github.com/rxi/json.lua)) doesn't work well due to single-byte constraints for string functions.

However, I found a better Json tool named `JsonTableConverter` at **MoonSharp** that (de)serialization between table and json is done entirely in C#, doesn't produce this problem, and its performance is about **15** times higher than the pure lua json library, but we need to manually escape "\\/"

of course we can also use `JsonTableConverter` directly via `LuaUserData`, but it seems a little weird to use MoonSharp to register a type under MoonSharp.

**Comment by evilfactory** [comment]
Maybe instead of providing a new json tool, we can fix the issue in moonsharp? I found this PR on the moonsharp repository
https://github.com/moonsharp-devs/moonsharp/pull/184, which seems to fix it, i could merge it into my moonsharp fork, are you able to test if it works?

**Comment by zhu-rengong** [comment]
I have tested it, worked fine.

**Comment by evilfactory** [comment]
Alright, ima get into merging this tomorrow, or maybe today.

**Comment by zhu-rengong** [comment]
Nice, and I was surprised that moonsharp already provides json tool:
`json.parse` and `json.serialize`, which can be used directly.

**Comment by evilfactory** [comment]
By the way, it would be cool if you tested the latest version on [github](https://github.com/evilfactory/Barotrauma-lua-attempt/releases/tag/latest) to make sure the merged changes don't break anything badly.

**Comment by zhu-rengong** [comment]
at least in my tests it‘s ok 👌
