### ISSUE TITLE
System.InvalidOperationException: Cannot enter the same MoonSharp processor from two different threads

### ISSUE THREAD

**Issue by DoomOfMax97** [evilfactory/Barotrauma-lua-attempt#64]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The Game crashes, not only the server, but also game.

**Steps To Reproduce**
Wearing a longrange radio from EK Armory and then trying to wear the Military Mk-I Hardsuit, while being in a shuttle.
Since the mod doesn't use lua, I am reporting it here.

**Version**
Windows
Lua! Version: fd0c3ba19
Barotrauma:  v0.17.12.0 rev fd0c3ba19

**Additional information**
  [SV LUA ERROR] System.InvalidOperationException: Cannot enter the same MoonSharp processor from two different threads : 4 and 5
   at MoonSharp.Interpreter.Execution.VM.Processor.EnterProcessor()
   at MoonSharp.Interpreter.Execution.VM.Processor.Call(DynValue function, DynValue[] args)
   at Barotrauma.LuaCsSetup.CallLuaFunction(Object function, Object[] arguments)

**Comment by evilfactory** [comment]
What Lua mods were you using?

**Comment by DoomOfMax97** [comment]
Neurotrauma enabled,
Multiplayer crew manager and NeuroEyes disabled (their init still appears in the log tho)
[ThisIsASeriousServer_2022-04-22_1921.txt](https://github.com/evilfactory/Barotrauma-lua-attempt/files/8542854/ThisIsASeriousServer_2022-04-22_1921.txt)
)
Currently looking for the client log.

**Comment by DoomOfMax97** [comment]
[crashreport (2).log](https://github.com/evilfactory/Barotrauma-lua-attempt/files/8542876/crashreport.2.log)

**Comment by evilfactory** [comment]
What's the identifier of the long range radio?

**Comment by DoomOfMax97** [comment]
identifier="ekutility_longrangeradio"

**Comment by DoomOfMax97** [comment]
Maybe the radio is running on a different thread and this isn't handled correctly? On the other hand the normal radio (probably) work fine, unless they are able to cause the same error.

**Comment by evilfactory** [comment]
Were you in the respawn shuttle by any chance?

**Comment by DoomOfMax97** [comment]
Nope, a shuttle docked to the sub, which I undocked in the first area, with the main submarine still docked to the station.

**Comment by evilfactory** [comment]
Huh, are you able to reproduce this consistently?

**Comment by DoomOfMax97** [comment]
Haven't tried yet, one second.

**Comment by DoomOfMax97** [comment]
Yep

**Comment by evilfactory** [comment]
Can you send me the save file? I am unable to reproduce it

**Comment by DoomOfMax97** [comment]
Quickly doing a test with just the mods which seem to cause it.

**Comment by DoomOfMax97** [comment]
[Multiplayer.zip](https://github.com/evilfactory/Barotrauma-lua-attempt/files/8543069/Multiplayer.zip)

**Comment by evilfactory** [comment]
Question, how do i use the save? I added it to the Multiplayer folder in appdata but it doesn't show up in the campaign menu

**Comment by evilfactory** [comment]
I tried to start a fresh campaign with kastrull, undocked the drone, teleported to it, equipped the long range radio and Military Mk-I Hardsuit, and nothing

**Comment by DoomOfMax97** [comment]
What's your discord name and tag?

**Comment by evilfactory** [comment]
Evil Factory#5412

**Comment by evilfactory** [comment]
Crash fixed in https://github.com/evilfactory/Barotrauma-lua-attempt/commit/e77ef4de2627b1bbce951832813728e858bb6799, not actually a fix, more of a workaround, should prevent any crashes.
