### ISSUE TITLE
Looking to extend/abstract this

### ISSUE THREAD

**Issue by jesse-savary** [evilfactory/Barotrauma-lua-attempt#7]
Hey there, amazing work on this mod. I've been playing Barotrauma since legacy and it's very exciting to see someone working on integrating scripting capabilities into the game. 

I was wondering if you would be alright with me forking this project and abstracting away some of the Lua specific bits to add support for other languages, particularly Typescript (which is my daily driver).

**Comment by evilfactory** [comment]
Hey! Sorry i didn't notice the issue, feel free to fork the project, i don't have any problems with that.
