### ISSUE TITLE
lua and cs do not follow the same rules of starting

### ISSUE THREAD

**Issue by zhu-rengong** [evilfactory/Barotrauma-lua-attempt#71]
The starting process of the lua script:
1. Enabled Packages: lua files in the Autorun folder
2. Local Packages & All Packages: lua files in the ForcedAutorun folder

cs script:
Only Enabled Packages: lua files in the Mod folder

client's enabled packages will be set to the same as the server and ignore the config in settings, assume i let mod force to run in the mutliplayer, lua files should be placed under the ForcedAutorun folder, but as for cs files, they can't.

**Suggestion**
Perhaps an additional search path should be added for the cs script loader to ensure that the unenabled mod enforce running some cs files.

**Comment by oiltanker** [comment]
I cannot understand the issue you are describing.

**Comment by zhu-rengong** [comment]
I hate myself, a quick question instead of bad description that are painful to read:
If somebody joins a server that disable some mods that support c# but he enable, cs mod doesn't work due to related cs files are out of search pathes.

**Comment by oiltanker** [comment]
Well that falls into the issue, of him needing to have all mod dependencies.
Normally that does not mater, as all mods by default are server-side only. To run mods client-side an additional installation is needed. That means client would also have to install CsForBarotrauma Mod (https://steamcommunity.com/workshop/filedetails/?id=2795927223), meaning, every Cs mod must have it as a dependency. 
![image](https://user-images.githubusercontent.com/17730697/165735408-42bb5ca8-3d34-4abd-9c6a-3259b5a22e4e.png)

**Comment by zhu-rengong** [comment]
He installed both lfb and cfb and enabled them,
I mean any client's CS mod won't work on someone else's server.

**Comment by zhu-rengong** [comment]
absolutely not, and the issue has nothing to do with the path. I mean when we join a server other people hosted, the local EnabledPackages will become the same as the server we joined. This will cause the cs mod that we have enabled in the settings to not work.

**Comment by zhu-rengong** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2788338390
For example, this mod, its cs file can only be run in single player or the server that has this mod turned on, but join other people's servers, if it doesn't have this mod enabled, then the mod on the client side will not be enabled.

**Comment by oiltanker** [comment]
Plus that would prevent such things as cheats. At least, as far as, C# mods are concerned.
